question_data = [
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "The 2010 film 'The Social Network' is a biographical drama film about MySpace founder Tom Anderson.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Minions was released on the June 10th, 2015.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "The film '2001: A Space Odyssey' was released on December 31st, 2000.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Samuel L. Jackson had the words, 'Bad Motherf*cker' in-scripted on his lightsaber during the filming of Star Wars.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Actor Tommy Chong served prison time.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Brandon Routh plays the titular character in the movie 'John Wick'.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Shaquille O'Neal appeared in the 1997 film 'Space Jam'.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Foodfight! earned less than $80,000 at box office.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Leonardo DiCaprio won an Oscar for Best Actor in 2004's 'The Aviator'.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean",
     "difficulty": "easy",
     "category": "Entertainment: Film",
     "question": "Han Solo's co-pilot and best friend, Chewbacca, is an Ewok.",
     "correct_answer": "False",
     "incorrect_answers": ["True"]}]
